import urllib.request


def get_elements(text, file):
    frases = str(text, "ISO-8859-1").split("\n")
    for frase in frases:
        if not frase:
            continue

        palavras = frase.split(" ")

        for palavra in palavras:
            if 'class="f">' in palavra:
                verb = palavra.split("</span>")
                v = verb[0]
                file.write(v.replace('class="f">', '') + "\n")


url = "https://www.conjugacao.com.br/verbo-xxx/"

verbs_infinitive = ["amar",
                    "comer",
                    "partir",
                    "falar",
                    "cantar",
                    "estudar",
                    "correr",
                    "vender",
                    "beber",
                    "escrever",
                    "andar",
                    "agir",
                    "chegar",
                    "ficar",
                    "gostar",
                    "brincar",
                    "abrir",
                    "viver",
                    "jogar",
                    "comprar",
                    "corrigir",
                    "receber",
                    "pensar",
                    "dancar",
                    "viajar",
                    "passar",
                    "conhecer",
                    "comecar",
                    "assistir",
                    "aprender",
                    "encontrar",
                    "dividir",
                    "trabalhar",
                    "levar",
                    "chamar",
                    "dever",
                    "precisar",
                    "deixar",
                    "voar",
                    "voltar",
                    "pular",
                    "passear",
                    "entender",
                    "nascer",
                    "lembrar",
                    "usar",
                    "olhar",
                    "parar",
                    "achar",
                    "dirigir",
                    "esquecer",
                    "acordar",
                    "colocar",
                    "proteger",
                    "morar",
                    "fingir",
                    "esperar",
                    "ganhar",
                    "descer",
                    "cumprir",
                    "mexer",
                    "conjugar",
                    "morrer",
                    "conversar",
                    "bater",
                    "pegar",
                    "contar",
                    "tomar",
                    "entrar",
                    "mandar",
                    "possuir",
                    "chorar",
                    "imprimir",
                    "desejar",
                    "ajudar",
                    "lavar",
                    "continuar",
                    "chover",
                    "doer",
                    "sonhar",
                    "procurar",
                    "acabar",
                    "atender",
                    "existir",
                    "nadar",
                    "doar",
                    "colorir",
                    "caminhar",
                    "decidir",
                    "pagar",
                    "mudar",
                    "acontecer",
                    "entreter",
                    "almocar",
                    "desistir",
                    "suar",
                    "fechar",
                    "participar",
                    "escolher",
                    "falir",
                    "avisar",
                    "realizar",
                    "responder",
                    "encher",
                    "vencer",
                    "parecer",
                    "crescer",
                    "tornar",
                    "permitir",
                    "sentar",
                    "enviar",
                    "perdoar",
                    "ligar",
                    "buscar",
                    "sofrer",
                    "terminar",
                    "apresentar",
                    "tirar",
                    "casar",
                    "agradecer",
                    "adquirir",
                    "convidar",
                    "entregar",
                    "levantar",
                    "precaver",
                    "perceber",
                    "informar",
                    "criar",
                    "perguntar",
                    "feder",
                    "ensinar",
                    "aceitar",
                    "tentar",
                    "beijar",
                    "aproveitar",
                    "mostrar",
                    "respeitar",
                    "pentear",
                    "julgar",
                    "matar",
                    "gritar",
                    "aparecer",
                    "zoar",
                    "excluir",
                    "acreditar",
                    "surgir",
                    "resolver",
                    "visitar",
                    "permanecer",
                    "discutir"]

f = open("verbs.txt", mode="a", encoding="ISO-8859-1")
for i in verbs_infinitive:

    f.write(i + "\n")

    contents = urllib.request.urlopen(url.replace("xxx", i)).read()
    get_elements(contents, f)

f.close()
